// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: model.proto

package modelpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Model represents a machine learning model
type Model struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Framework     string                 `protobuf:"bytes,5,opt,name=framework,proto3" json:"framework,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Size          int64                  `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	Checksum      string                 `protobuf:"bytes,8,opt,name=checksum,proto3" json:"checksum,omitempty"`
	StoragePath   string                 `protobuf:"bytes,9,opt,name=storage_path,json=storagePath,proto3" json:"storage_path,omitempty"`
	DockerImage   string                 `protobuf:"bytes,10,opt,name=docker_image,json=dockerImage,proto3" json:"docker_image,omitempty"`
	Tags          []string               `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	OwnerId       string                 `protobuf:"bytes,12,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,13,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	IsPublic      bool                   `protobuf:"varint,14,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{0}
}

func (x *Model) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Model) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Model) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Model) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Model) GetFramework() string {
	if x != nil {
		return x.Framework
	}
	return ""
}

func (x *Model) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Model) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Model) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *Model) GetStoragePath() string {
	if x != nil {
		return x.StoragePath
	}
	return ""
}

func (x *Model) GetDockerImage() string {
	if x != nil {
		return x.DockerImage
	}
	return ""
}

func (x *Model) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Model) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Model) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Model) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *Model) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Model) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateModelRequest is the request for CreateModel
type CreateModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Framework     string                 `protobuf:"bytes,4,opt,name=framework,proto3" json:"framework,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	OwnerId       string                 `protobuf:"bytes,7,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,8,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	IsPublic      bool                   `protobuf:"varint,9,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateModelRequest) Reset() {
	*x = CreateModelRequest{}
	mi := &file_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelRequest) ProtoMessage() {}

func (x *CreateModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModelRequest.ProtoReflect.Descriptor instead.
func (*CreateModelRequest) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{1}
}

func (x *CreateModelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateModelRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateModelRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CreateModelRequest) GetFramework() string {
	if x != nil {
		return x.Framework
	}
	return ""
}

func (x *CreateModelRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateModelRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateModelRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateModelRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateModelRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

// CreateModelResponse is the response for CreateModel
type CreateModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         *Model                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateModelResponse) Reset() {
	*x = CreateModelResponse{}
	mi := &file_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelResponse) ProtoMessage() {}

func (x *CreateModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModelResponse.ProtoReflect.Descriptor instead.
func (*CreateModelResponse) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{2}
}

func (x *CreateModelResponse) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

// GetModelRequest is the request for GetModel
type GetModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelRequest) Reset() {
	*x = GetModelRequest{}
	mi := &file_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelRequest) ProtoMessage() {}

func (x *GetModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelRequest.ProtoReflect.Descriptor instead.
func (*GetModelRequest) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{3}
}

func (x *GetModelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetModelResponse is the response for GetModel
type GetModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         *Model                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelResponse) Reset() {
	*x = GetModelResponse{}
	mi := &file_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelResponse) ProtoMessage() {}

func (x *GetModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelResponse.ProtoReflect.Descriptor instead.
func (*GetModelResponse) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{4}
}

func (x *GetModelResponse) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

// ListModelsRequest is the request for ListModels
type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Framework     string                 `protobuf:"bytes,2,opt,name=framework,proto3" json:"framework,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	OwnerId       string                 `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	IsPublic      bool                   `protobuf:"varint,7,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	Page          int32                  `protobuf:"varint,8,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,9,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{5}
}

func (x *ListModelsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListModelsRequest) GetFramework() string {
	if x != nil {
		return x.Framework
	}
	return ""
}

func (x *ListModelsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListModelsRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ListModelsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListModelsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ListModelsRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *ListModelsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListModelsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListModelsResponse is the response for ListModels
type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*Model               `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{6}
}

func (x *ListModelsResponse) GetModels() []*Model {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *ListModelsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListModelsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListModelsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// UpdateModelRequest is the request for UpdateModel
type UpdateModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IsPublic      bool                   `protobuf:"varint,6,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateModelRequest) Reset() {
	*x = UpdateModelRequest{}
	mi := &file_model_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModelRequest) ProtoMessage() {}

func (x *UpdateModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateModelRequest.ProtoReflect.Descriptor instead.
func (*UpdateModelRequest) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateModelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateModelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateModelRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateModelRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateModelRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UpdateModelRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

// UpdateModelResponse is the response for UpdateModel
type UpdateModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         *Model                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateModelResponse) Reset() {
	*x = UpdateModelResponse{}
	mi := &file_model_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModelResponse) ProtoMessage() {}

func (x *UpdateModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateModelResponse.ProtoReflect.Descriptor instead.
func (*UpdateModelResponse) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateModelResponse) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

// DeleteModelRequest is the request for DeleteModel
type DeleteModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteModelRequest) Reset() {
	*x = DeleteModelRequest{}
	mi := &file_model_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteModelRequest) ProtoMessage() {}

func (x *DeleteModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteModelRequest.ProtoReflect.Descriptor instead.
func (*DeleteModelRequest) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteModelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// UpdateModelStatusRequest is the request for UpdateModelStatus
type UpdateModelStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateModelStatusRequest) Reset() {
	*x = UpdateModelStatusRequest{}
	mi := &file_model_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateModelStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModelStatusRequest) ProtoMessage() {}

func (x *UpdateModelStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateModelStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateModelStatusRequest) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateModelStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateModelStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// UpdateModelStatusResponse is the response for UpdateModelStatus
type UpdateModelStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         *Model                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateModelStatusResponse) Reset() {
	*x = UpdateModelStatusResponse{}
	mi := &file_model_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateModelStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModelStatusResponse) ProtoMessage() {}

func (x *UpdateModelStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateModelStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateModelStatusResponse) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateModelStatusResponse) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

// AddModelTagsRequest is the request for AddModelTags
type AddModelTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddModelTagsRequest) Reset() {
	*x = AddModelTagsRequest{}
	mi := &file_model_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddModelTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddModelTagsRequest) ProtoMessage() {}

func (x *AddModelTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddModelTagsRequest.ProtoReflect.Descriptor instead.
func (*AddModelTagsRequest) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{12}
}

func (x *AddModelTagsRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *AddModelTagsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// RemoveModelTagsRequest is the request for RemoveModelTags
type RemoveModelTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveModelTagsRequest) Reset() {
	*x = RemoveModelTagsRequest{}
	mi := &file_model_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveModelTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveModelTagsRequest) ProtoMessage() {}

func (x *RemoveModelTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveModelTagsRequest.ProtoReflect.Descriptor instead.
func (*RemoveModelTagsRequest) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveModelTagsRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *RemoveModelTagsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// SetModelMetadataRequest is the request for SetModelMetadata
type SetModelMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetModelMetadataRequest) Reset() {
	*x = SetModelMetadataRequest{}
	mi := &file_model_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetModelMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetModelMetadataRequest) ProtoMessage() {}

func (x *SetModelMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetModelMetadataRequest.ProtoReflect.Descriptor instead.
func (*SetModelMetadataRequest) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{14}
}

func (x *SetModelMetadataRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *SetModelMetadataRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// GetModelMetadataRequest is the request for GetModelMetadata
type GetModelMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelMetadataRequest) Reset() {
	*x = GetModelMetadataRequest{}
	mi := &file_model_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelMetadataRequest) ProtoMessage() {}

func (x *GetModelMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetModelMetadataRequest) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{15}
}

func (x *GetModelMetadataRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

// GetModelMetadataResponse is the response for GetModelMetadata
type GetModelMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      map[string]string      `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelMetadataResponse) Reset() {
	*x = GetModelMetadataResponse{}
	mi := &file_model_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelMetadataResponse) ProtoMessage() {}

func (x *GetModelMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetModelMetadataResponse) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{16}
}

func (x *GetModelMetadataResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_model_proto protoreflect.FileDescriptor

const file_model_proto_rawDesc = "" +
	"\n" +
	"\vmodel.proto\x12\x05model\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xf2\x03\n" +
	"\x05Model\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1c\n" +
	"\tframework\x18\x05 \x01(\tR\tframework\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x12\n" +
	"\x04size\x18\a \x01(\x03R\x04size\x12\x1a\n" +
	"\bchecksum\x18\b \x01(\tR\bchecksum\x12!\n" +
	"\fstorage_path\x18\t \x01(\tR\vstoragePath\x12!\n" +
	"\fdocker_image\x18\n" +
	" \x01(\tR\vdockerImage\x12\x12\n" +
	"\x04tags\x18\v \x03(\tR\x04tags\x12\x19\n" +
	"\bowner_id\x18\f \x01(\tR\aownerId\x12\x1b\n" +
	"\ttenant_id\x18\r \x01(\tR\btenantId\x12\x1b\n" +
	"\tis_public\x18\x0e \x01(\bR\bisPublic\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xed\x02\n" +
	"\x12CreateModelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1c\n" +
	"\tframework\x18\x04 \x01(\tR\tframework\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12C\n" +
	"\bmetadata\x18\x06 \x03(\v2'.model.CreateModelRequest.MetadataEntryR\bmetadata\x12\x19\n" +
	"\bowner_id\x18\a \x01(\tR\aownerId\x12\x1b\n" +
	"\ttenant_id\x18\b \x01(\tR\btenantId\x12\x1b\n" +
	"\tis_public\x18\t \x01(\bR\bisPublic\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"9\n" +
	"\x13CreateModelResponse\x12\"\n" +
	"\x05model\x18\x01 \x01(\v2\f.model.ModelR\x05model\"!\n" +
	"\x0fGetModelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"6\n" +
	"\x10GetModelResponse\x12\"\n" +
	"\x05model\x18\x01 \x01(\v2\f.model.ModelR\x05model\"\xf0\x01\n" +
	"\x11ListModelsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tframework\x18\x02 \x01(\tR\tframework\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\tR\aownerId\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x1b\n" +
	"\tis_public\x18\a \x01(\bR\bisPublic\x12\x12\n" +
	"\x04page\x18\b \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\t \x01(\x05R\x05limit\"z\n" +
	"\x12ListModelsResponse\x12$\n" +
	"\x06models\x18\x01 \x03(\v2\f.model.ModelR\x06models\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\x8d\x02\n" +
	"\x12UpdateModelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12C\n" +
	"\bmetadata\x18\x05 \x03(\v2'.model.UpdateModelRequest.MetadataEntryR\bmetadata\x12\x1b\n" +
	"\tis_public\x18\x06 \x01(\bR\bisPublic\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"9\n" +
	"\x13UpdateModelResponse\x12\"\n" +
	"\x05model\x18\x01 \x01(\v2\f.model.ModelR\x05model\"$\n" +
	"\x12DeleteModelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"B\n" +
	"\x18UpdateModelStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"?\n" +
	"\x19UpdateModelStatusResponse\x12\"\n" +
	"\x05model\x18\x01 \x01(\v2\f.model.ModelR\x05model\"D\n" +
	"\x13AddModelTagsRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\"G\n" +
	"\x16RemoveModelTagsRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\"\xbb\x01\n" +
	"\x17SetModelMetadataRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12H\n" +
	"\bmetadata\x18\x02 \x03(\v2,.model.SetModelMetadataRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"4\n" +
	"\x17GetModelMetadataRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\"\xa2\x01\n" +
	"\x18GetModelMetadataResponse\x12I\n" +
	"\bmetadata\x18\x01 \x03(\v2-.model.GetModelMetadataResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xe3\x05\n" +
	"\fModelService\x12D\n" +
	"\vCreateModel\x12\x19.model.CreateModelRequest\x1a\x1a.model.CreateModelResponse\x12;\n" +
	"\bGetModel\x12\x16.model.GetModelRequest\x1a\x17.model.GetModelResponse\x12A\n" +
	"\n" +
	"ListModels\x12\x18.model.ListModelsRequest\x1a\x19.model.ListModelsResponse\x12D\n" +
	"\vUpdateModel\x12\x19.model.UpdateModelRequest\x1a\x1a.model.UpdateModelResponse\x12@\n" +
	"\vDeleteModel\x12\x19.model.DeleteModelRequest\x1a\x16.google.protobuf.Empty\x12V\n" +
	"\x11UpdateModelStatus\x12\x1f.model.UpdateModelStatusRequest\x1a .model.UpdateModelStatusResponse\x12B\n" +
	"\fAddModelTags\x12\x1a.model.AddModelTagsRequest\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\x0fRemoveModelTags\x12\x1d.model.RemoveModelTagsRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\x10SetModelMetadata\x12\x1e.model.SetModelMetadataRequest\x1a\x16.google.protobuf.Empty\x12S\n" +
	"\x10GetModelMetadata\x12\x1e.model.GetModelMetadataRequest\x1a\x1f.model.GetModelMetadataResponseB8Z6github.com/17882237881/MaaS/shared/proto/model;modelpbb\x06proto3"

var (
	file_model_proto_rawDescOnce sync.Once
	file_model_proto_rawDescData []byte
)

func file_model_proto_rawDescGZIP() []byte {
	file_model_proto_rawDescOnce.Do(func() {
		file_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_proto_rawDesc), len(file_model_proto_rawDesc)))
	})
	return file_model_proto_rawDescData
}

var file_model_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_model_proto_goTypes = []any{
	(*Model)(nil),                     // 0: model.Model
	(*CreateModelRequest)(nil),        // 1: model.CreateModelRequest
	(*CreateModelResponse)(nil),       // 2: model.CreateModelResponse
	(*GetModelRequest)(nil),           // 3: model.GetModelRequest
	(*GetModelResponse)(nil),          // 4: model.GetModelResponse
	(*ListModelsRequest)(nil),         // 5: model.ListModelsRequest
	(*ListModelsResponse)(nil),        // 6: model.ListModelsResponse
	(*UpdateModelRequest)(nil),        // 7: model.UpdateModelRequest
	(*UpdateModelResponse)(nil),       // 8: model.UpdateModelResponse
	(*DeleteModelRequest)(nil),        // 9: model.DeleteModelRequest
	(*UpdateModelStatusRequest)(nil),  // 10: model.UpdateModelStatusRequest
	(*UpdateModelStatusResponse)(nil), // 11: model.UpdateModelStatusResponse
	(*AddModelTagsRequest)(nil),       // 12: model.AddModelTagsRequest
	(*RemoveModelTagsRequest)(nil),    // 13: model.RemoveModelTagsRequest
	(*SetModelMetadataRequest)(nil),   // 14: model.SetModelMetadataRequest
	(*GetModelMetadataRequest)(nil),   // 15: model.GetModelMetadataRequest
	(*GetModelMetadataResponse)(nil),  // 16: model.GetModelMetadataResponse
	nil,                               // 17: model.CreateModelRequest.MetadataEntry
	nil,                               // 18: model.UpdateModelRequest.MetadataEntry
	nil,                               // 19: model.SetModelMetadataRequest.MetadataEntry
	nil,                               // 20: model.GetModelMetadataResponse.MetadataEntry
	(*timestamppb.Timestamp)(nil),     // 21: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),             // 22: google.protobuf.Empty
}
var file_model_proto_depIdxs = []int32{
	21, // 0: model.Model.created_at:type_name -> google.protobuf.Timestamp
	21, // 1: model.Model.updated_at:type_name -> google.protobuf.Timestamp
	17, // 2: model.CreateModelRequest.metadata:type_name -> model.CreateModelRequest.MetadataEntry
	0,  // 3: model.CreateModelResponse.model:type_name -> model.Model
	0,  // 4: model.GetModelResponse.model:type_name -> model.Model
	0,  // 5: model.ListModelsResponse.models:type_name -> model.Model
	18, // 6: model.UpdateModelRequest.metadata:type_name -> model.UpdateModelRequest.MetadataEntry
	0,  // 7: model.UpdateModelResponse.model:type_name -> model.Model
	0,  // 8: model.UpdateModelStatusResponse.model:type_name -> model.Model
	19, // 9: model.SetModelMetadataRequest.metadata:type_name -> model.SetModelMetadataRequest.MetadataEntry
	20, // 10: model.GetModelMetadataResponse.metadata:type_name -> model.GetModelMetadataResponse.MetadataEntry
	1,  // 11: model.ModelService.CreateModel:input_type -> model.CreateModelRequest
	3,  // 12: model.ModelService.GetModel:input_type -> model.GetModelRequest
	5,  // 13: model.ModelService.ListModels:input_type -> model.ListModelsRequest
	7,  // 14: model.ModelService.UpdateModel:input_type -> model.UpdateModelRequest
	9,  // 15: model.ModelService.DeleteModel:input_type -> model.DeleteModelRequest
	10, // 16: model.ModelService.UpdateModelStatus:input_type -> model.UpdateModelStatusRequest
	12, // 17: model.ModelService.AddModelTags:input_type -> model.AddModelTagsRequest
	13, // 18: model.ModelService.RemoveModelTags:input_type -> model.RemoveModelTagsRequest
	14, // 19: model.ModelService.SetModelMetadata:input_type -> model.SetModelMetadataRequest
	15, // 20: model.ModelService.GetModelMetadata:input_type -> model.GetModelMetadataRequest
	2,  // 21: model.ModelService.CreateModel:output_type -> model.CreateModelResponse
	4,  // 22: model.ModelService.GetModel:output_type -> model.GetModelResponse
	6,  // 23: model.ModelService.ListModels:output_type -> model.ListModelsResponse
	8,  // 24: model.ModelService.UpdateModel:output_type -> model.UpdateModelResponse
	22, // 25: model.ModelService.DeleteModel:output_type -> google.protobuf.Empty
	11, // 26: model.ModelService.UpdateModelStatus:output_type -> model.UpdateModelStatusResponse
	22, // 27: model.ModelService.AddModelTags:output_type -> google.protobuf.Empty
	22, // 28: model.ModelService.RemoveModelTags:output_type -> google.protobuf.Empty
	22, // 29: model.ModelService.SetModelMetadata:output_type -> google.protobuf.Empty
	16, // 30: model.ModelService.GetModelMetadata:output_type -> model.GetModelMetadataResponse
	21, // [21:31] is the sub-list for method output_type
	11, // [11:21] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_model_proto_init() }
func file_model_proto_init() {
	if File_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_proto_rawDesc), len(file_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_model_proto_goTypes,
		DependencyIndexes: file_model_proto_depIdxs,
		MessageInfos:      file_model_proto_msgTypes,
	}.Build()
	File_model_proto = out.File
	file_model_proto_goTypes = nil
	file_model_proto_depIdxs = nil
}
