// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.0
// source: model.proto

package modelpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Model represents a machine learning model
type Model struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Version     string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Framework   string                 `protobuf:"bytes,5,opt,name=framework,proto3" json:"framework,omitempty"`
	Status      string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Size        int64                  `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	Checksum    string                 `protobuf:"bytes,8,opt,name=checksum,proto3" json:"checksum,omitempty"`
	StoragePath string                 `protobuf:"bytes,9,opt,name=storage_path,json=storagePath,proto3" json:"storage_path,omitempty"`
	DockerImage string                 `protobuf:"bytes,10,opt,name=docker_image,json=dockerImage,proto3" json:"docker_image,omitempty"`
	Tags        []string               `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	OwnerId     string                 `protobuf:"bytes,12,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	TenantId    string                 `protobuf:"bytes,13,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	IsPublic    bool                   `protobuf:"varint,14,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Model) Reset() {
	*x = Model{}
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Model) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Model) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Model) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Model) GetFramework() string {
	if x != nil {
		return x.Framework
	}
	return ""
}

func (x *Model) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Model) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// CreateModelRequest is the request for CreateModel
type CreateModelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string            `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Version     string            `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Framework   string            `protobuf:"bytes,4,opt,name=framework,proto3" json:"framework,omitempty"`
	Tags        []string          `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata    map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	OwnerId     string            `protobuf:"bytes,7,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	TenantId    string            `protobuf:"bytes,8,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	IsPublic    bool              `protobuf:"varint,9,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
}

func (x *CreateModelRequest) Reset() {
	*x = CreateModelRequest{}
}

func (x *CreateModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelRequest) ProtoMessage() {}

func (x *CreateModelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateModelRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateModelRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CreateModelRequest) GetFramework() string {
	if x != nil {
		return x.Framework
	}
	return ""
}

func (x *CreateModelRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateModelRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateModelRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateModelRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateModelRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

// CreateModelResponse is the response for CreateModel
type CreateModelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model *Model `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
}

func (x *CreateModelResponse) Reset() {
	*x = CreateModelResponse{}
}

func (x *CreateModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelResponse) ProtoMessage() {}

func (x *CreateModelResponse) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

// GetModelRequest is the request for GetModel
type GetModelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetModelRequest) Reset() {
	*x = GetModelRequest{}
}

func (x *GetModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelRequest) ProtoMessage() {}

func (x *GetModelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetModelResponse is the response for GetModel
type GetModelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model *Model `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
}

func (x *GetModelResponse) Reset() {
	*x = GetModelResponse{}
}

func (x *GetModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelResponse) ProtoMessage() {}

func (x *GetModelResponse) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

// ListModelsRequest is the request for ListModels
type ListModelsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Framework string   `protobuf:"bytes,2,opt,name=framework,proto3" json:"framework,omitempty"`
	Status    string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	OwnerId   string   `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	TenantId  string   `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Tags      []string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	IsPublic  bool     `protobuf:"varint,7,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	Page      int32    `protobuf:"varint,8,opt,name=page,proto3" json:"page,omitempty"`
	Limit     int32    `protobuf:"varint,9,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListModelsRequest) GetFramework() string {
	if x != nil {
		return x.Framework
	}
	return ""
}

func (x *ListModelsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListModelsRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ListModelsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListModelsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ListModelsRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *ListModelsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListModelsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListModelsResponse is the response for ListModels
type ListModelsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Models []*Model `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	Total  int64    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page   int32    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit  int32    `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) GetModels() []*Model {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *ListModelsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListModelsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListModelsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// UpdateModelRequest is the request for UpdateModel
type UpdateModelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string            `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Tags        []string          `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata    map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	IsPublic    bool              `protobuf:"varint,6,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
}

func (x *UpdateModelRequest) Reset() {
	*x = UpdateModelRequest{}
}

func (x *UpdateModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModelRequest) ProtoMessage() {}

func (x *UpdateModelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateModelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateModelRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateModelRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateModelRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UpdateModelRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

// UpdateModelResponse is the response for UpdateModel
type UpdateModelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model *Model `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
}

func (x *UpdateModelResponse) Reset() {
	*x = UpdateModelResponse{}
}

func (x *UpdateModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModelResponse) ProtoMessage() {}

func (x *UpdateModelResponse) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

// DeleteModelRequest is the request for DeleteModel
type DeleteModelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteModelRequest) Reset() {
	*x = DeleteModelRequest{}
}

func (x *DeleteModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteModelRequest) ProtoMessage() {}

func (x *DeleteModelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// UpdateModelStatusRequest is the request for UpdateModelStatus
type UpdateModelStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *UpdateModelStatusRequest) Reset() {
	*x = UpdateModelStatusRequest{}
}

func (x *UpdateModelStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModelStatusRequest) ProtoMessage() {}

func (x *UpdateModelStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateModelStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// UpdateModelStatusResponse is the response for UpdateModelStatus
type UpdateModelStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model *Model `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
}

func (x *UpdateModelStatusResponse) Reset() {
	*x = UpdateModelStatusResponse{}
}

func (x *UpdateModelStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModelStatusResponse) ProtoMessage() {}

func (x *UpdateModelStatusResponse) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

// AddModelTagsRequest is the request for AddModelTags
type AddModelTagsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModelId string   `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Tags    []string `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *AddModelTagsRequest) Reset() {
	*x = AddModelTagsRequest{}
}

func (x *AddModelTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddModelTagsRequest) ProtoMessage() {}

func (x *AddModelTagsRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *AddModelTagsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// RemoveModelTagsRequest is the request for RemoveModelTags
type RemoveModelTagsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModelId string   `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Tags    []string `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *RemoveModelTagsRequest) Reset() {
	*x = RemoveModelTagsRequest{}
}

func (x *RemoveModelTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveModelTagsRequest) ProtoMessage() {}

func (x *RemoveModelTagsRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *RemoveModelTagsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// SetModelMetadataRequest is the request for SetModelMetadata
type SetModelMetadataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModelId  string            `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Metadata map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *SetModelMetadataRequest) Reset() {
	*x = SetModelMetadataRequest{}
}

func (x *SetModelMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetModelMetadataRequest) ProtoMessage() {}

func (x *SetModelMetadataRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *SetModelMetadataRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// GetModelMetadataRequest is the request for GetModelMetadata
type GetModelMetadataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModelId string `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
}

func (x *GetModelMetadataRequest) Reset() {
	*x = GetModelMetadataRequest{}
}

func (x *GetModelMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelMetadataRequest) ProtoMessage() {}

func (x *GetModelMetadataRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

// GetModelMetadataResponse is the response for GetModelMetadata
type GetModelMetadataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metadata map[string]string `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetModelMetadataResponse) Reset() {
	*x = GetModelMetadataResponse{}
}

func (x *GetModelMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelMetadataResponse) ProtoMessage() {}

func (x *GetModelMetadataResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_model_proto protoreflect.FileDescriptor

var file_model_proto_rawDesc = []byte{
	// This is a placeholder - in real scenario this would contain binary protobuf descriptor
}

var (
	file_model_proto_goTypes = []interface{}{
		(*Model)(nil),                     // 0: model.Model
		(*CreateModelRequest)(nil),        // 1: model.CreateModelRequest
		(*CreateModelResponse)(nil),       // 2: model.CreateModelResponse
		(*GetModelRequest)(nil),           // 3: model.GetModelRequest
		(*GetModelResponse)(nil),          // 4: model.GetModelResponse
		(*ListModelsRequest)(nil),         // 5: model.ListModelsRequest
		(*ListModelsResponse)(nil),        // 6: model.ListModelsResponse
		(*UpdateModelRequest)(nil),        // 7: model.UpdateModelRequest
		(*UpdateModelResponse)(nil),       // 8: model.UpdateModelResponse
		(*DeleteModelRequest)(nil),        // 9: model.DeleteModelRequest
		(*UpdateModelStatusRequest)(nil),  // 10: model.UpdateModelStatusRequest
		(*UpdateModelStatusResponse)(nil), // 11: model.UpdateModelStatusResponse
		(*AddModelTagsRequest)(nil),       // 12: model.AddModelTagsRequest
		(*RemoveModelTagsRequest)(nil),    // 13: model.RemoveModelTagsRequest
		(*SetModelMetadataRequest)(nil),   // 14: model.SetModelMetadataRequest
		(*GetModelMetadataRequest)(nil),   // 15: model.GetModelMetadataRequest
		(*GetModelMetadataResponse)(nil),  // 16: model.GetModelMetadataResponse
		(*timestamppb.Timestamp)(nil),     // 17: google.protobuf.Timestamp
		(*emptypb.Empty)(nil),             // 18: google.protobuf.Empty
	}
)
